name = "casteneda-flooring"
compatibility_date = "2024-01-15"
pages_build_output_dir = "."

[env.production]
name = "casteneda-flooring"

[env.staging]
name = "{{CLIENT_NAME_SLUG}}-staging"

# Custom headers for better performance and security
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
for = "*.jpg"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.jpeg"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.png"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.webp"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.svg"
[headers.values]
Cache-Control = "public, max-age=31536000"

# Redirects for SPA routing (if needed)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
