name: Localhost Servers Release

on:
  push:
    branches:
      - main
    paths:
      - 'localhost_servers/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate timestamp version
        id: version
        run: |
          timestamp=$(date +'%Y.%m.%d.%H%M%S')
          echo "timestamp=$timestamp" >> $GITHUB_OUTPUT
          echo "tag=servers-$timestamp" >> $GITHUB_OUTPUT

      - name: Create servers.zip (tracked files only)
        run: |
          mkdir release
          git ls-files localhost_servers | zip -@ release/servers.zip

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Authenticate GH CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create new dated release
        run: |
          gh release create ${{ steps.version.outputs.tag }} release/servers.zip \
            --title "Localhost Servers ${{ steps.version.outputs.timestamp }}" \
            --notes "Current release of Neurite's localhost servers"

      - name: Delete older servers-* releases (keep latest)
        run: |
          gh release list --limit 100 --json tagName,createdAt \
          | jq -r '.[] | select(.tagName | startswith("servers-")) | "\(.createdAt) \(.tagName)"' \
          | sort -r \
          | tail -n +2 \
          | awk '{print $2}' \
          | xargs -r -n 1 gh release delete -y
