name = "qieos-api"
main = "src/index.ts"
compatibility_date = "2025-01-27"

[vars]
SUPABASE_URL = ""
SUPABASE_SERVICE_ROLE_KEY = ""
OPENAI_API_KEY = ""
STRIPE_SECRET_KEY = ""
JWT_ISSUER = "qieos"
EMBEDDING_DIM = "1536"

[[r2_buckets]]
binding = "R2"
bucket_name = "qieos-files"
preview_bucket_name = "qieos-files-dev"

[env.production]
name = "qieos-api"

[env.staging]
name = "qieos-api-staging"
